### ISSUE TITLE
Gahshomar dos't show in elementary os 

### ISSUE THREAD

**Issue by money71** [Gahshomar/gahshomar#15]
hi 
Installed gahshomar from ppa.
icon is in slingshot.
After run gahshomar in terminal:

    :~$ gahshomar 
    (process:2965): GLib-WARNING **: /build/buildd/glib2.0-2.42.2/./glib/goption.c:2254: ignoring invalid short option '\xa0' (-96) in entry (null):quit

    ** (gahshomar:2965): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-J55pvvlxwp: Connection refused
    Traceback (most recent call last):
      File "<frozen importlib._bootstrap>", line 2135, in _find_spec
    AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/x86_64-linux-gnu/gahshomar/plugins/main/main.py", line 6, in <module>
        from gi.repository import GObject, Peas, Gtk, Gio, GLib, Gdk
      File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
        'introspection typelib not found' % namespace)
    ImportError: cannot import name Peas, introspection typelib not found

    (gahshomar:2965): libpeas-WARNING **: Error loading plugin 'main'

    (gahshomar:2965): Gtk-CRITICAL **: gtk_window_present_with_time: assertion 'GTK_IS_WINDOW (window)' failed

**Comment by 183amir** [comment]
Is `gir1.2-peas-1.0` package installed on your computer?

**Comment by money71** [comment]
thanks.
show gahshomar but not show indicator.
terminal :

~$ gahshomar 

    (process:4399): GLib-WARNING **: /build/buildd/glib2.0-2.42.2/./glib/goption.c:2254: ignoring invalid short option '\xa0' (-96) in entry (null):quit

    ** (gahshomar:4399): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-J55pvvlxwp: Connection refused
    INFO:gahshomar.window:minimized is: False
    ^C

**Comment by 183amir** [comment]
Try enabling it from the Preferences->Plugins->Appindicator

**Comment by money71** [comment]
I can't find Preferences->Plugins->Appindicator
when run gahshomar, just show 
![workspace 1_004](https://cloud.githubusercontent.com/assets/6740968/8474469/8cf92672-20c5-11e5-9469-19f85ce1890c.png)

**Comment by 183amir** [comment]
Just installed Elementary OS Freya. How come you do not have the icon like mine?
![screenshot from 2015-07-02 19-14-16](https://cloud.githubusercontent.com/assets/5738695/8474921/dd75ceec-20ee-11e5-9696-81888df4ff52.png)
![screenshot from 2015-07-02 19-14-26](https://cloud.githubusercontent.com/assets/5738695/8474920/dd7545f8-20ee-11e5-81f8-428e303bcb21.png)

**Comment by 183amir** [comment]
If you can't find the menu, you can enable plugins like this from terminal:

    dconf write /org/gahshomar/Gahshomar/enabled-plugins "'appindicator'"

**Comment by money71** [comment]
yes, i Installed Elementary OS Freya.
I found It. after change windows control with tweak and change to default, i found it

**Comment by 183amir** [comment]
I'm glad that it worked.
