### ISSUE TITLE
 Problem with icon

### ISSUE THREAD

**Issue by ghost** [Gahshomar/gahshomar#19]
Hi, I have installed persian-calendar, but I can't see the icon on Unity panel. There is only a text that shows date. I'm using Ubuntu 14.04, I have installed version 4.4.0 from ppa.

**Comment by 183amir** [comment]
I replaced the icon with an invisible icon, I thought having only text in
the panel would be much cleaner.

**Comment by Aref-Alikhani** [comment]
Maybe, but I think if you add more options in preference menu will be better.

Thanks

**Comment by 183amir** [comment]
An option to opt for the icon in the panel?

**Comment by Aref-Alikhani** [comment]
Yeah of course! why not?! I think in this step the main window is not so important, I think you should focus on features like "special events" and like this... Have a good time

**Comment by 183amir** [comment]
I do not want to add calendar like features. I want to keep it like a simple calendar converter app for now.

**Comment by goodosuser** [comment]
سلام
خوب بود راهنما هم برای اجرا می گذاشتید هر چند شاید بدیهی باشه به نظرتون

**Comment by goodosuser** [comment]
پیشنهاد می کنم برای صفحه ورود هم فکری بشه تا قبل از ورود هم بشه تقویم شمسی رو داشت.
الان دیگه ویندوز هم داره
