### ISSUE TITLE
provide packages for ubuntu 16.04

### ISSUE THREAD

**Issue by z-avanes** [Gahshomar/gahshomar#21]
hi
i have problem in ubuntu 16.04 and get this error

(process:9436): GLib-WARNING **: /build/glib2.0-t9oPgV/glib2.0-2.48.0/./glib/goption.c:2367: ignoring invalid short option '\xc0' (-64) in entry (null):quit
/usr/lib/gahshomar/plugins/main/main.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, Gtk, Gio, GLib, Gdk
Traceback (most recent call last):
  File "/usr/lib/gahshomar/plugins/main/main.py", line 54, in do_activate
    from gahshomar.window import Window
ImportError: No module named 'gahshomar'

(gahshomar:9436): Gtk-CRITICAL **: gtk_window_present_with_time: assertion 'GTK_IS_WINDOW (window)' failed

how can fix this issue?

**Comment by 183amir** [comment]
How did you install Gahshomar?

**Comment by z-avanes** [comment]
first install from opensuse repository and have problem
now with manual installation problem fix
thx

**Comment by 183amir** [comment]
I have not released packages for Ubuntu 16.04. I will release them in a few weeks.

**Comment by Thatoo** [comment]
I'm waiting for this great app!
I'll try the manual installation but packages are so nice :-)

**Comment by Thatoo** [comment]
it works with manual install but it's not friendly to do so....

**Comment by 183amir** [comment]
I have been busy with my job I'll try to look at it on Sunday.

**Comment by 183amir** [comment]
I finally released the packages for Ubuntu 16.04. https://software.opensuse.org/download.html?project=home:183amir&package=gahshomar
