### ISSUE TITLE
 Invalid id gahshomar Names must contain at least 2 periods

### ISSUE THREAD

**Issue by saeedtabrizi** [Gahshomar/gahshomar#22]
Hi , 
I got the following error in ubuntu 16.04 :
`flatpak run gahshomar`

`error: Invalid id gahshomar: Names must contain at least 2 periods`

is there any problem with ubuntu ?

**Comment by 183amir** [comment]
No the flatpak name is not gahshomar. It is `org.gahshomar.Gahshomar`

If this works, feel free to edit the wiki and mention it there.

**Comment by saeedtabrizi** [comment]
Thanks @183amir 
its good running now .
