### ISSUE TITLE
Adding support for Aghan month names

### ISSUE THREAD

**Issue by 183amir** [Gahshomar/gahshomar#23]
https://en.wikipedia.org/wiki/Solar_Hijri_calendar#Month_names

**Comment by giftedwon** [comment]
I would like to see Afghanistan Persian Added to the Calendar.  Afghan's can read the Farsi Months but they have different names for the months here.

**Comment by 183amir** [comment]
Fixed in https://github.com/Gahshomar/gahshomar/releases/tag/v4.5.0. The shell extension does not support afghan month names yet but the rest of the app do.
