### ISSUE TITLE
Installation Error: No package 'libpeas-1.0' found

### ISSUE THREAD

**Issue by ahangarha** [Gahshomar/gahshomar#24]
I tried to install v4.4.1. I got the source code from github (clone --depth 1). I think I have all the dependencies. First error I received was: 

```
./autogen.sh 
/usr/bin/gnome-autogen.sh
***Warning*** PKG_NAME is deprecated, you may remove it from autogen.sh
checking for automake >= 1.11.2...
  testing automake... found 1.15
checking for autoreconf >= 2.53...
  testing autoreconf... found 2.69
checking for glib-gettext >= 2.2.0...
  testing glib-gettextize... found 2.52.0
checking for intltool >= 0.25...
  testing intltoolize... found 0.51.0
checking for pkg-config >= 0.14.0...
  testing pkg-config... found 0.29.1
Checking for required M4 macros...
  yelp.m4 not found
***Error***: some autoconf macros required to build org.gahshomar.Gahshomar
  were not found in your aclocal path, or some forbidden
  macros were found.  Perhaps you need to adjust your
  ACLOCAL_PATH?
```

I solved it by installing `yelp-tools` (so I think this needs to be added to the list of dependencies)

But still get the following error (just pasting last few lines):

```
checking for GAHSHOMAR... no
configure: error: Package requirements (gtk+-3.0 >= 3.10.0, glib-2.0 >= 2.34, libpeas-1.0, libpeas-gtk-1.0) were not met:

No package 'libpeas-1.0' found
No package 'libpeas-gtk-1.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GAHSHOMAR_CFLAGS
and GAHSHOMAR_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

This is while I have `libpeas` installed on my system:

```
dpkg -l | grep libpeas
ii  libpeas-1.0-0:amd64       1.20.0-1     amd64     Application plugin library
ii  libpeas-common            1.20.0-1     all       Application plugin library (common files)
```

What am I doing wrong?

**Comment by 183amir** [comment]
Couple of things:
1. Why not install 4.5.1? I removed the pre-release tag.
2. Why not install using flatpak?
3. You probably need to install the `-devel` or `-dev` packages too.
Please feel free to edit the Wiki after you install it.

**Comment by ahangarha** [comment]
I could manage to install the app by installing two packages:

- `libpeas-dev`
- `libjalali-dev`

So, I think these two, along with `yelp-tools` need to be added to dependencies as well.

**Comment by ahangarha** [comment]
I didn't go for 4.5.1 version because of the pre-released tag.
I tried flatpak but I needed to download above 130MB which made me consider building from source code.

Thanks

**Comment by 183amir** [comment]
Ok. Glad it worked for you.
