### ISSUE TITLE
Cannot run the app on Kubuntu 17.04

### ISSUE THREAD

**Issue by ahangarha** [Gahshomar/gahshomar#25]
I successfully installed Gahshomar 4.4.1 from source code on my Kubuntu 17.04 64-bit. But I cannot run it.

Running the app from terminal gives the following error:

```
➜  ~  gahshomar                  

(process:29520): GLib-WARNING **: ../../../../glib/goption.c:2393: ignoring no-arg, optional-arg or filename flags (21936) on option of arg-type 0 in entry (null):quit
/usr/local/lib/gahshomar/plugins/main/main.py:7: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, Gtk, Gio, GLib, Gdk
Traceback (most recent call last):
  File "/usr/local/lib/gahshomar/plugins/main/main.py", line 54, in do_activate
    from gahshomar.window import Window
ImportError: No module named 'gahshomar'

(gahshomar:29520): Gtk-CRITICAL **: gtk_window_present_with_time: assertion 'GTK_IS_WINDOW (window)' failed
```

**Comment by 183amir** [comment]
I still recommend the flatpak installation.

Could you please paste here the output of `sudo make install` command when you ran it?

**Comment by ahangarha** [comment]
I have access only to this much of it https://paste.ubuntu.com/25634118/

**Comment by 183amir** [comment]
When you do `python3 -c 'import gahshomar', what happens?

**Comment by ahangarha** [comment]
```
➜  ~ python3 -c 'import gahshomar'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'gahshomar'
```

**Comment by 183amir** [comment]
Your log says that gahsomar is installed in `/usr/local/lib/python3.5/site-packages/gahshomar/` but I don't know why you can't import it.

**Comment by ahangarha** [comment]
Couldn't it be solved by restarting the system?

**Comment by 183amir** [comment]
I don't know what's wrong. It's up to you to figure it out. You can try the flatpak installation instead and let me if that doesn't work. I can't help you with this.

**Comment by ahangarha** [comment]
I couldn't get any success in installing the app manually.

I installed it using flatpak. It works now but I have some minor problems. I might ask them here if I cannot find the solution other places. (including app indicator icon which is not visible in tray, and app size which is bigger than what it should be, so I need to resize it)

Thank you for the help.

**Comment by 183amir** [comment]
Hi @ahangarha, if you have problems with the flatpak installation still, please open another issue. I am interested in maintaining the flatpak installation.
