### ISSUE TITLE
Application does not run under Ubuntu 18 with XFCE 4 desktop

### ISSUE THREAD

**Issue by pvonmoradi** [Gahshomar/gahshomar#30]
I'm using manual method in Ubuntu 18:bionic beaver with xfce4 deskop.
Launching Gahshomar from app launcher does not bring up the program (or any process/daemon). Launching the binary from terminal throws these:
```
/usr/bin$ sudo ./gahshomar 

(process:5967): GLib-WARNING **: 21:44:34.235: ../../../../glib/goption.c:2376: ignoring invalid short option '\xc0' (-64) in entry (null):quit

(process:5967): GLib-WARNING **: 21:44:34.236: ../../../../glib/goption.c:2393: ignoring no-arg, optional-arg or filename flags (21872) on option of arg-type 0 in entry (null):quit

(gahshomar:5967): libpeas-CRITICAL **: 21:44:34.388: peas_engine_load_plugin: assertion 'info != NULL' failed

(gahshomar:5967): Gtk-CRITICAL **: 21:44:34.388: gtk_window_present_with_time: assertion 'GTK_IS_WINDOW (window)' failed

```
For installation, I've used `sudo ./configure --prefix=/usr` and `sudo make` then `sudo make install`.
I also had to manually install other dependencies like `libpeas-dev` and `libjalali-dev` and some other packages when autotools complained they are missing.

Thanks for your help :)

**Comment by 183amir** [comment]
Thank you for reporting the issue. Have you considered using flatpak?

**Comment by pvonmoradi** [comment]
@183amir Thanks for your fast response ;)
Yeah but it was downloading too much dependencies so I cancelled it.

**Comment by 183amir** [comment]
Could you please try with that ?

**Comment by pvonmoradi** [comment]
OK I might look into that some time in future :)

**Comment by 183amir** [comment]
Gahshomar is released into flathub.org and from now on this will be the only supported way of installing it: https://flathub.org/apps/details/org.gahshomar.Gahshomar
