### ISSUE TITLE
flatpak version deps are end of life 

### ISSUE THREAD

**Issue by rezad1393** [Gahshomar/gahshomar#42]
when installing from flatpak (a very good way to distribute and thank you for using it) the app uses gnome38 runtime/org.gnome.Platform/x86_64/3.38 and which is end of life and it takes end of life deps from repos.
like:
Info: runtime org.freedesktop.Platform.GL.default branch 20.08 is end-of-life, with reason:

can you update those?

**Comment by 183amir** [comment]
It needs to be updated in https://github.com/flathub/org.gahshomar.Gahshomar but I don't remember how to do it.

**Comment by 183amir** [comment]
should be fixed in https://github.com/flathub/org.gahshomar.Gahshomar/pull/3

**Comment by rezad1393** [comment]
> should be fixed in [flathub/org.gahshomar.Gahshomar#3](https://github.com/flathub/org.gahshomar.Gahshomar/pull/3)

خدا بهت اجر بده.

**Comment by rezad1393** [comment]
is this app no longer developed or is it just bug free?
